export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <p>Inner kub</p>
      {children}
    </div>
  )
}

export default AuthLayout
