import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import Back from '@/_components/Back'
import StoreProvider from './StoreProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <header
            style={{
              textAlign: 'center',
              backgroundColor: 'lightblue',
              padding: '1rem',
            }}

            // className="flex min-h-screen flex-col items-center w-full p-24 bg-gray-300"
          >
            <p>Header</p>
          </header>
          {children}

          <Back />

          <footer
            style={{
              textAlign: 'center',
              backgroundColor: 'ghostwhite',
              padding: '1rem',
            }}
          >
            <p>Footer</p>
          </footer>
        </body>
      </html>
    </StoreProvider>
  )
}
